services:
  hyperliquid-monitor:
    build: .
    restart: always
    user: "65534:65534"
    env_file:
      - ./.env
    volumes:
      # - ./data:/app/data # If you want to persist data outside the container
      - ./addresses.txt:/app/addresses.txt # If you want to manage addresses.txt outside the container
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test: ["CMD-SHELL", "find /tmp/healthcheck.txt -mmin -5 | grep . || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 5
